ENV_VARS = {
    'COINBASE_PRO_TRADE_API_KEY': '',
    'COINBASE_PRO_TRADE_API_KEY_PASSPHRASE': '',
    'COINBASE_PRO_TRADE_API_KEY_SECRET': '',

    'COINBASE_PRO_TRANSFER_VIEW_API_KEY': '',
    'COINBASE_PRO_TRANSFER_VIEW_API_KEY_PASSPHRASE': '',
    'COINBASE_PRO_TRANSFER_VIEW_API_KEY_SECRET': '',

    'COINBASE_PRO_VIEW_API_KEY': '',
    'COINBASE_PRO_VIEW_API_KEY_PASSPHRASE': '',
    'COINBASE_PRO_VIEW_API_KEY_SECRET': '',
}
